
// Objective-C API for talking to the following Go packages
//
//	SDK
//
// File is generated by gomobile bind. Do not edit.
#ifndef __DVPNSDK_FRAMEWORK_H__
#define __DVPNSDK_FRAMEWORK_H__

#include "Norsedvpnsdk.objc.h"
#include "Universe.objc.h"

#endif
