// Objective-C API for talking to SDK Go package.
//   gobind -lang=objc SDK
//
// File is generated by gobind. Do not edit.

#ifndef __Norsedvpnsdk_H__
#define __Norsedvpnsdk_H__

@import Foundation;
#include "ref.h"
#include "Universe.objc.h"


@class NorsedvpnsdkDVPNSDK;

@interface NorsedvpnsdkDVPNSDK : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nullable instancetype)init:(NSString* _Nullable)appToken appSecret:(NSString* _Nullable)appSecret configurationKey:(NSString* _Nullable)configurationKey;
@property (nonatomic) NSString* _Nonnull appToken;
@property (nonatomic) NSString* _Nonnull appSecret;
- (NSData* _Nullable)activateDevice:(NSString* _Nullable)accessToken deviceId:(NSString* _Nullable)deviceId error:(NSError* _Nullable* _Nullable)error;
- (NSData* _Nullable)createCredentialsForCity:(NSString* _Nullable)accessToken cityId:(NSString* _Nullable)cityId protocol:(NSString* _Nullable)protocol error:(NSError* _Nullable* _Nullable)error;
- (NSData* _Nullable)createCredentialsForServer:(NSString* _Nullable)accessToken serverId:(NSString* _Nullable)serverId error:(NSError* _Nullable* _Nullable)error;
- (NSData* _Nullable)getCities:(NSString* _Nullable)accessToken countryId:(NSString* _Nullable)countryId protocol:(NSString* _Nullable)protocol error:(NSError* _Nullable* _Nullable)error;
- (NSData* _Nullable)getCity:(NSString* _Nullable)accessToken cityId:(NSString* _Nullable)cityId error:(NSError* _Nullable* _Nullable)error;
- (NSData* _Nullable)getConnectionDetails:(NSError* _Nullable* _Nullable)error;
- (NSData* _Nullable)getCountries:(NSString* _Nullable)accessToken protocol:(NSString* _Nullable)protocol error:(NSError* _Nullable* _Nullable)error;
- (NSData* _Nullable)getCountry:(NSString* _Nullable)accessToken countryId:(NSString* _Nullable)countryId error:(NSError* _Nullable* _Nullable)error;
- (NSData* _Nullable)getServer:(NSString* _Nullable)accessToken serverId:(NSString* _Nullable)serverId error:(NSError* _Nullable* _Nullable)error;
- (NSData* _Nullable)getServers:(NSString* _Nullable)accessToken cityId:(NSString* _Nullable)cityId sort:(NSString* _Nullable)sort protocol:(NSString* _Nullable)protocol offset:(long)offset limit:(long)limit error:(NSError* _Nullable* _Nullable)error;
- (void)probe;
- (NSData* _Nullable)registerDevice:(NSString* _Nullable)platform error:(NSError* _Nullable* _Nullable)error;
@end

FOUNDATION_EXPORT NorsedvpnsdkDVPNSDK* _Nullable NorsedvpnsdkNewDVPNSDK(NSString* _Nullable appToken, NSString* _Nullable appSecret, NSString* _Nullable configurationKey);

#endif
